In [2]:
import os
import sys
import pathlib
import time

import numpy as np
import pandas as pd 

In [3]:
cwd = pathlib.Path().resolve()
src = cwd.parent
root = src.parent
sys.path.append(str(src))

In [4]:
def normalize_training_data(
        save_path,
        normalize_test_data=True,
        normalize_train_validation_data=True,
):
    


    statistics = pd.DataFrame()
    
    return statistics

def get_scalings(sim_number, 
                 sim_letter='o',
                 folder='data/augmented_data/',
                 timestep=-1,
                 include_velocities=False):
    """Gets mean and variance for a given simulation. These are calculated for the DEM, VX, VY, WD. 
    The statistics for the DEM are constant throughout a simulation.
    The statistics for the VX, VY, WD are calculated from the LAST timestep of a simulation.
    "folder" refers to the folder containing the DEM, VX, VY, WD folders.
    "timestep" refers to the timestep to use when calculating the normalization parameters for VX, VY, WD.
    "include_velocities": set to True in order to also calculate statistics for velocities.
    """

    stats = {}

    DEM_path = folder + f'DEM/DEM_{str(int(sim_number))}_{str(sim_letter)}.txt'
    WD_path = folder + f'WD/WD_{str(int(sim_number))}_{str(sim_letter)}.txt'

    with open(DEM_path, 'r') as file:
        data = np.loadtxt(file)[:,-1]

        mean = np.mean(data)
        std = np.std(data)
        minimum = np.min(data)
        maximum = np.max(data)

        stats['DEM'] = {'mean':mean,
                        'std':std,
                        'min':minimum,
                        'max':maximum}
        
    with open(WD_path, 'r') as file:
        data = np.loadtxt(file)[:,-1]

        mean = np.mean(data)
        std = np.std(data)
        minimum = np.min(data)
        maximum = np.max(data)

        stats['WD'] = {'mean':mean,
                       'std':std,
                       'min':minimum,
                       'max':maximum}

    if include_velocities:
        VX_path = folder + f'VX/VX_{str(int(sim_number))}_{str(sim_letter)}.txt'
        VY_path = folder + f'VY/VY_{str(int(sim_number))}_{str(sim_letter)}.txt'

        with open(VX_path, 'r') as file:
            data = np.loadtxt(file)[:,-1]

            mean = np.mean(data)
            std = np.std(data)
            minimum = np.min(data)
            maximum = np.max(data)

            stats['VX'] = {'mean':mean,
                           'std':std,
                           'min':minimum,
                           'max':maximum}
            
        with open(VY_path, 'r') as file:
            data = np.loadtxt(file)[:,-1]

            mean = np.mean(data)
            std = np.std(data)
            minimum = np.min(data)
            maximum = np.max(data)

            stats['VY'] = {'mean':mean,
                           'std':std,
                           'min':minimum,
                           'max':maximum}
    return stats




In [16]:


folder_path = str(root) + "/data/augmented_data/"
DEM_path = folder_path + "DEM/DEM_1_o.txt"
print(DEM_path)

with open(DEM_path, 'r') as DEM_file:
    DEM = np.loadtxt(DEM_file)[:,-1]
    mean = np.mean()
    std = np.std()
    


C:\Users\khdeb\Projects\DS-AI/data/augmented_data/DEM/DEM_1_o.txt
[[ 0.      -0.43378 -0.97414 ...  1.39494  1.19744  0.88844]
 [ 0.37679 -0.05384 -0.587   ...  1.30936  0.99169  0.58494]
 [ 0.70629  0.29072 -0.22081 ...  1.12016  0.68503  0.18876]
 ...
 [-0.17492 -0.33368 -0.61968 ...  1.12394  1.04505  0.79886]
 [-0.1829  -0.2944  -0.52223 ...  0.62891  0.64647  0.5163 ]
 [-0.16543 -0.23838 -0.42058 ...  0.25557  0.37452  0.35797]]
(64, 64)


In [19]:
folder_path = str(root) + "/data/augmented_data/"
WD_path = folder_path + "WD/WD_1_o.txt"
print(WD_path)

with open(WD_path, 'r') as file:
    data = np.loadtxt(file)[:, -1]
    print(data)
    print(data.shape)
    # mean = np.mean()
    # std = np.std()

C:\Users\khdeb\Projects\DS-AI/data/augmented_data/WD/WD_1_o.txt
[0.     0.     0.     ... 0.     1.0697 0.    ]
(4096,)
